import React from 'react';
import Icon from './ui/icon';

interface DisclaimerBannerProps {
    compact?: boolean;
}

const DisclaimerBanner: React.FC<DisclaimerBannerProps> = ({ compact }) => {
    if (compact) {
        return (
            <p className="text-[10px] text-muted-foreground text-center font-mono leading-relaxed">
                AI-generated analysis. Not legal advice. Always consult a qualified legal professional.
            </p>
        );
    }

    return (
        <div className="bg-muted/60 border border-border rounded-lg px-4 py-3 flex items-start gap-3">
            <Icon name="info" size="sm" className="text-muted-foreground shrink-0 mt-0.5" />
            <p className="text-xs text-muted-foreground leading-relaxed">
                <span className="font-bold">Disclaimer:</span> This analysis is generated by AI and is provided for informational purposes only.
                It does not constitute legal advice. Always consult a qualified legal professional before making decisions based on this analysis.
            </p>
        </div>
    );
};

export default DisclaimerBanner;
