"""Lightweight email service for sending PDF reports via SMTP."""

import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders

from app.core.config import settings

logger = logging.getLogger(__name__)


def is_email_configured() -> bool:
    return bool(settings.SMTP_HOST and settings.SMTP_USER and settings.SMTP_PASSWORD)


def send_report_email(
    to_email: str,
    pdf_bytes: bytes,
    filename: str,
    report_type: str = "full",
    risk_score: int | None = None,
) -> None:
    """Send analysis PDF report to the given email address."""
    if not is_email_configured():
        raise RuntimeError("SMTP is not configured. Set SMTP_HOST, SMTP_USER, and SMTP_PASSWORD in .env")

    from_email = settings.SMTP_FROM_EMAIL or settings.SMTP_USER
    from_name = settings.SMTP_FROM_NAME

    msg = MIMEMultipart()
    msg["From"] = f"{from_name} <{from_email}>"
    msg["To"] = to_email
    msg["Subject"] = f"Legal Assist — {report_type.title()} Analysis Report"

    # Email body
    score_line = f"\nOverall Risk Score: {risk_score}/100" if risk_score is not None else ""
    body = (
        f"Hello,\n\n"
        f"Please find attached your {report_type} legal analysis report for \"{filename}\".{score_line}\n\n"
        f"This report was generated by Legal Assist AI.\n\n"
        f"— Legal Assist Team\n\n"
        f"Note: This is an automated email. The attached report was generated by AI and should be reviewed by a legal professional."
    )
    msg.attach(MIMEText(body, "plain"))

    # Attach PDF
    attachment = MIMEBase("application", "pdf")
    attachment.set_payload(pdf_bytes)
    encoders.encode_base64(attachment)
    safe_filename = filename.replace('"', "").replace("/", "_")[:80]
    attachment.add_header("Content-Disposition", f'attachment; filename="report_{safe_filename}.pdf"')
    msg.attach(attachment)

    # Send
    with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=30) as server:
        server.starttls()
        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.send_message(msg)

    logger.info("Report email sent to %s for file %s", to_email, filename)
